# Generated by Django 4.0.4 on 2022-05-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='詳細情報'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='latitude',
            field=models.FloatField(verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='longitude',
            field=models.FloatField(verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='bakery',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='review_bakery', to='main.bakery', verbose_name='店名'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/asovi_app/img', verbose_name='写真'),
        ),
    ]
