# Generated by Django 4.0.4 on 2022-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bakery_info_alter_bakery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='追加日時'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿日時'),
        ),
    ]
